[build]
# https://github.com/rust-lang/rust/pull/124129
# https://github.com/dtolnay/linkme/pull/88
rustflags = ["-C", "target-cpu=native", "-Z", "linker-features=-lld"]

# https://docs.rs/embuild/latest/embuild/cargo/fn.workspace_dir.html
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
